### ISSUE TITLE
Création du connecteur pour LMAX

### ISSUE THREAD

**Issue by bynicodevelop** [traderbook/trading-platform#9]
* Nom du connecteur : "Lmax Exchange"

Ce connecteur doit permettre d'implémente l'interface d'API `IConnector`. Dans sa première version, ce connecteur doit permettre : 

* L'authentification
* La récupération des instruments et de leurs cotations

**Comment by traderbook** [comment]
Issue dépréciée et pas suffisamment spécifiées
